### ISSUE TITLE
Resnet structure in the code?

### ISSUE THREAD

**Issue by EnJiang** [dizcza/lbcnn.pytorch#1]
I noticed the following snippet in your code of class BlockLBP
```python
    def forward(self, x):
        residual = x
        x = self.batch_norm(x)
        x = F.relu(self.conv_lbp(x))
        x = self.conv_1x1(x)
        x.add_(residual)
        return x
```
seem a resnet structure(shortcut), I'm not sure if this is exactly what they used in the paper?

**Comment by dizcza** [comment]
yes, they used resnet
so do I
